[package]
name = "pricing_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
tokio = { version = "1.37", features = ["full"] }
